vim.keymap.set('n', '<leader>gs', vim.cmd.Git)
vim.keymap.set('n', '<leader>gl', function()
	vim.cmd("G log --oneline --graph --decorate")
end)
vim.keymap.set('n', '<leader>gb', function()
	vim.cmd("G branch")
end)
vim.keymap.set('n', '<leader>blame', function()
	vim.cmd("G blame")
end)
